import type { Category, Clearance, FurnitureType, Placement, Shape } from '../types';

export interface FurniturePreset {
  id: string;
  /** Product name in the furniture browser (generic catalog). */
  label: string;
  /** Default name of placed items. */
  name: string;
  type: FurnitureType;
  category: Category;
  width: number;
  depth: number;
  height: number;
  placement: Placement;
  /** Also stands on the other: on furniture when dropped onto it, on the floor elsewhere. */
  flexiblePlacement?: boolean;
  rotation?: number;
  clearance?: Partial<Clearance>;
  shape?: Shape;
  /** Placed items get this color instead of their category's (plants are green). */
  color?: string;
}

const ROUND: Shape = { kind: 'round' };

/** Chairs pulled up all around a round table. */
const ROUND_TABLE_CLEARANCE = { enabled: false, front: 70, back: 70, left: 70, right: 70 } as const;

const desk = (width: number): FurniturePreset => ({
  id: `desk-${width}`,
  label: 'Desk',
  name: 'Desk',
  type: 'desk',
  category: 'desk',
  width,
  depth: 80,
  height: 75,
  placement: 'floor',
  clearance: { enabled: false, front: 90 },
});

export const MONITOR_SIZES = [
  { label: '24″', inches: 24, width: 54, depth: 18, height: 42 },
  { label: '27″', inches: 27, width: 61, depth: 20, height: 46 },
  { label: '32″', inches: 32, width: 72, depth: 23, height: 53 },
] as const;

const monitor = (m: (typeof MONITOR_SIZES)[number]): FurniturePreset => ({
  id: `monitor-${m.inches}`,
  label: `Monitor ${m.label}`,
  name: `Monitor ${m.label}`,
  type: 'monitor',
  category: 'electronics',
  width: m.width,
  depth: m.depth,
  height: m.height,
  placement: 'surface',
});

/** Typical TVs of each size on their own stand: width, stand depth, height. */
export const TV_SIZES = [
  { label: '43″', inches: 43, width: 97, depth: 20, height: 63 },
  { label: '50″', inches: 50, width: 112, depth: 25, height: 71 },
  { label: '55″', inches: 55, width: 123, depth: 25, height: 78 },
  { label: '65″', inches: 65, width: 145, depth: 29, height: 91 },
  { label: '75″', inches: 75, width: 167, depth: 36, height: 104 },
] as const;

const tv = (t: (typeof TV_SIZES)[number]): FurniturePreset => ({
  id: `tv-${t.inches}`,
  label: `TV ${t.label}`,
  name: `TV ${t.label}`,
  type: 'tv',
  category: 'electronics',
  width: t.width,
  depth: t.depth,
  height: t.height,
  placement: 'surface',
});

/** Foliage color of plants (their leaves are drawn in darker shades of it). */
const PLANT_GREEN = '#b5d0a1';

/** Standard desk widths for the one-click size switcher. */
export const DESK_WIDTHS = [140, 160, 180, 200] as const;

/** Mattress widths of the generic beds (all 200 cm long). 140 keeps the original id "bed". */
const BED_WIDTHS = [90, 140, 160, 180] as const;

const bed = (width: (typeof BED_WIDTHS)[number]): FurniturePreset => ({
  id: width === 140 ? 'bed' : `bed-${width}`,
  label: 'Bed',
  name: 'Bed',
  type: 'bed',
  category: 'bed',
  width,
  depth: 200,
  height: 45,
  placement: 'floor',
  clearance: { enabled: false, left: 60, right: 60, front: 60 },
});

/** Standard kitchen worktop depth and height (base cabinets including the worktop). */
const COUNTER = { depth: 60, height: 90 } as const;

/** Front clearance of kitchen counters: a comfortable working aisle. */
const KITCHEN_AISLE = { enabled: false, front: 100 } as const;

/** Appliance doors (dishwasher, washing machine, fridge) need their swing kept clear. */
const APPLIANCE_DOOR = { enabled: true, front: 60 } as const;

export const PRESETS: readonly FurniturePreset[] = [
  ...DESK_WIDTHS.map(desk),
  {
    id: 'sit-stand-desk',
    label: 'Sit-stand desk',
    name: 'Sit-stand desk',
    type: 'sit-stand-desk',
    category: 'desk',
    width: 180,
    depth: 80,
    height: 72,
    placement: 'floor',
    clearance: { enabled: false, front: 90 },
  },
  {
    id: 'l-desk',
    label: 'L-shaped desk',
    name: 'L-shaped desk',
    type: 'l-desk',
    category: 'desk',
    width: 160,
    depth: 120,
    height: 75,
    placement: 'floor',
    shape: { kind: 'l', segment: 60, returnWidth: 60, returnSide: 'right' },
    clearance: { enabled: false, front: 90 },
  },
  {
    id: 'office-chair',
    label: 'Office chair',
    name: 'Office chair',
    type: 'office-chair',
    category: 'seating',
    width: 65,
    depth: 65,
    height: 115,
    placement: 'floor',
    // Rotated so the seat faces a desk placed against the top wall.
    rotation: 180,
    clearance: { enabled: true, back: 40 },
  },
  {
    id: 'dining-chair',
    label: 'Dining chair',
    name: 'Chair',
    type: 'chair',
    category: 'seating',
    width: 45,
    depth: 52,
    height: 88,
    placement: 'floor',
    clearance: { enabled: false, back: 40 },
  },
  {
    id: 'armchair',
    label: 'Armchair',
    name: 'Armchair',
    type: 'armchair',
    category: 'seating',
    width: 85,
    depth: 85,
    height: 80,
    placement: 'floor',
    clearance: { enabled: false, front: 60 },
  },
  {
    id: 'sofa-2-seat',
    label: '2-seat sofa',
    name: 'Sofa',
    type: 'sofa',
    category: 'bed',
    width: 160,
    depth: 90,
    height: 85,
    placement: 'floor',
    clearance: { enabled: false, front: 60 },
  },
  {
    id: 'sofa',
    label: 'Sofa',
    name: 'Sofa',
    type: 'sofa',
    category: 'bed',
    width: 200,
    depth: 90,
    height: 85,
    placement: 'floor',
    clearance: { enabled: false, front: 60 },
  },
  {
    id: 'sofa-3-seat',
    label: '3-seat sofa',
    name: 'Sofa',
    type: 'sofa',
    category: 'bed',
    width: 230,
    depth: 95,
    height: 85,
    placement: 'floor',
    clearance: { enabled: false, front: 60 },
  },
  {
    id: 'sofa-chaise',
    label: 'Sofa with chaise longue',
    name: 'Sofa with chaise',
    type: 'sofa',
    category: 'bed',
    width: 240,
    depth: 160,
    height: 85,
    placement: 'floor',
    shape: { kind: 'l', segment: 95, returnWidth: 95, returnSide: 'right' },
    clearance: { enabled: false, front: 60 },
  },
  {
    id: 'corner-sofa',
    label: 'Corner sofa (L-shaped)',
    name: 'Corner sofa',
    type: 'sofa',
    category: 'bed',
    width: 260,
    depth: 200,
    height: 85,
    placement: 'floor',
    shape: { kind: 'l', segment: 95, returnWidth: 95, returnSide: 'right' },
    clearance: { enabled: false, front: 60 },
  },
  ...BED_WIDTHS.map(bed),
  {
    id: 'coffee-table',
    label: 'Coffee table',
    name: 'Coffee table',
    type: 'table',
    category: 'desk',
    width: 110,
    depth: 60,
    height: 45,
    placement: 'floor',
  },
  {
    id: 'side-table',
    label: 'Side table',
    name: 'Side table',
    type: 'table',
    category: 'desk',
    width: 45,
    depth: 45,
    height: 50,
    placement: 'floor',
  },
  {
    id: 'dining-table-120',
    label: 'Dining table',
    name: 'Dining table',
    type: 'table',
    category: 'desk',
    width: 120,
    depth: 80,
    height: 75,
    placement: 'floor',
    clearance: { enabled: false, front: 70, back: 70 },
  },
  {
    id: 'dining-table',
    label: 'Dining table',
    name: 'Dining table',
    type: 'table',
    category: 'desk',
    width: 160,
    depth: 90,
    height: 75,
    placement: 'floor',
    clearance: { enabled: false, front: 70, back: 70 },
  },
  {
    id: 'dining-table-200',
    label: 'Dining table',
    name: 'Dining table',
    type: 'table',
    category: 'desk',
    width: 200,
    depth: 100,
    height: 75,
    placement: 'floor',
    clearance: { enabled: false, front: 70, back: 70 },
  },
  {
    id: 'round-dining-table-90',
    label: 'Round dining table',
    name: 'Dining table',
    type: 'table',
    category: 'desk',
    width: 90,
    depth: 90,
    height: 75,
    placement: 'floor',
    shape: ROUND,
    clearance: ROUND_TABLE_CLEARANCE,
  },
  {
    id: 'round-dining-table-120',
    label: 'Round dining table',
    name: 'Dining table',
    type: 'table',
    category: 'desk',
    width: 120,
    depth: 120,
    height: 75,
    placement: 'floor',
    shape: ROUND,
    clearance: ROUND_TABLE_CLEARANCE,
  },
  {
    id: 'oval-dining-table',
    label: 'Oval dining table',
    name: 'Dining table',
    type: 'table',
    category: 'desk',
    width: 180,
    depth: 100,
    height: 75,
    placement: 'floor',
    shape: ROUND,
    clearance: { enabled: false, front: 70, back: 70 },
  },
  {
    id: 'round-coffee-table',
    label: 'Round coffee table',
    name: 'Coffee table',
    type: 'table',
    category: 'desk',
    width: 80,
    depth: 80,
    height: 45,
    placement: 'floor',
    shape: ROUND,
  },
  {
    id: 'round-side-table',
    label: 'Round side table',
    name: 'Side table',
    type: 'table',
    category: 'desk',
    width: 45,
    depth: 45,
    height: 50,
    placement: 'floor',
    shape: ROUND,
  },
  {
    id: 'pouf',
    label: 'Pouf',
    name: 'Pouf',
    type: 'pouf',
    category: 'seating',
    width: 50,
    depth: 50,
    height: 42,
    placement: 'floor',
    shape: ROUND,
  },
  {
    id: 'stool',
    label: 'Stool',
    name: 'Stool',
    type: 'pouf',
    category: 'seating',
    width: 35,
    depth: 35,
    height: 45,
    placement: 'floor',
    shape: ROUND,
  },
  {
    id: 'bar-stool',
    label: 'Bar stool',
    name: 'Bar stool',
    type: 'pouf',
    category: 'seating',
    width: 40,
    depth: 40,
    height: 75,
    placement: 'floor',
    shape: ROUND,
  },
  {
    id: 'sideboard',
    label: 'Sideboard',
    name: 'Sideboard',
    type: 'sideboard',
    category: 'storage',
    width: 160,
    depth: 45,
    height: 80,
    placement: 'floor',
    clearance: { enabled: false, front: 50 },
  },
  {
    id: 'tv-bench',
    label: 'TV bench',
    name: 'TV bench',
    type: 'sideboard',
    category: 'storage',
    width: 180,
    depth: 40,
    height: 45,
    placement: 'floor',
    clearance: { enabled: false, front: 50 },
  },
  {
    id: 'chest-of-drawers',
    label: 'Chest of drawers',
    name: 'Chest of drawers',
    type: 'sideboard',
    category: 'storage',
    width: 80,
    depth: 48,
    height: 100,
    placement: 'floor',
    clearance: { enabled: false, front: 50 },
  },
  {
    id: 'nightstand',
    label: 'Nightstand',
    name: 'Nightstand',
    type: 'sideboard',
    category: 'storage',
    width: 45,
    depth: 40,
    height: 55,
    placement: 'floor',
  },
  {
    id: 'shoe-cabinet',
    label: 'Shoe cabinet',
    name: 'Shoe cabinet',
    type: 'sideboard',
    category: 'storage',
    width: 80,
    depth: 30,
    height: 100,
    placement: 'floor',
    clearance: { enabled: false, front: 50 },
  },
  {
    id: 'shelf',
    label: 'Shelf',
    name: 'Shelf',
    type: 'shelf',
    category: 'storage',
    width: 80,
    depth: 35,
    height: 180,
    placement: 'floor',
    clearance: { enabled: false, front: 50 },
  },
  {
    id: 'wardrobe',
    label: 'Wardrobe',
    name: 'Wardrobe',
    type: 'wardrobe',
    category: 'storage',
    width: 100,
    depth: 60,
    height: 200,
    placement: 'floor',
    clearance: { enabled: true, front: 60 },
  },
  {
    id: 'wardrobe-150',
    label: 'Wardrobe',
    name: 'Wardrobe',
    type: 'wardrobe',
    category: 'storage',
    width: 150,
    depth: 60,
    height: 200,
    placement: 'floor',
    clearance: { enabled: true, front: 60 },
  },
  {
    id: 'wardrobe-200',
    label: 'Wardrobe',
    name: 'Wardrobe',
    type: 'wardrobe',
    category: 'storage',
    width: 200,
    depth: 60,
    height: 200,
    placement: 'floor',
    clearance: { enabled: true, front: 60 },
  },
  // Kitchen. The first preset of a kind supplies that kind's defaults, so floor cabinets come first.
  {
    id: 'kitchen-base-cabinet',
    label: 'Kitchen base cabinet',
    name: 'Base cabinet',
    type: 'kitchen-cabinet',
    category: 'kitchen',
    width: 60,
    ...COUNTER,
    placement: 'floor',
    clearance: KITCHEN_AISLE,
  },
  {
    id: 'kitchen-counter',
    label: 'Kitchen counter',
    name: 'Kitchen counter',
    type: 'kitchen-cabinet',
    category: 'kitchen',
    width: 240,
    ...COUNTER,
    placement: 'floor',
    clearance: KITCHEN_AISLE,
  },
  {
    id: 'kitchen-counter-l',
    label: 'Kitchen counter (L-shaped)',
    name: 'Kitchen counter',
    type: 'kitchen-cabinet',
    category: 'kitchen',
    width: 240,
    depth: 180,
    height: COUNTER.height,
    placement: 'floor',
    shape: { kind: 'l', segment: COUNTER.depth, returnWidth: COUNTER.depth, returnSide: 'right' },
    clearance: KITCHEN_AISLE,
  },
  {
    id: 'kitchen-island',
    label: 'Kitchen island',
    name: 'Kitchen island',
    type: 'kitchen-cabinet',
    category: 'kitchen',
    width: 180,
    depth: 90,
    height: COUNTER.height,
    placement: 'floor',
    clearance: { enabled: false, front: 100, back: 100 },
  },
  {
    id: 'kitchen-tall-cabinet',
    label: 'Tall kitchen cabinet',
    name: 'Tall cabinet',
    type: 'kitchen-cabinet',
    category: 'kitchen',
    width: 60,
    depth: 60,
    height: 200,
    placement: 'floor',
    clearance: { enabled: false, front: 60 },
  },
  {
    // Hangs above the counter, so it doesn't collide with the base cabinets below.
    id: 'kitchen-wall-cabinet',
    label: 'Kitchen wall cabinet',
    name: 'Wall cabinet',
    type: 'kitchen-cabinet',
    category: 'kitchen',
    width: 60,
    depth: 35,
    height: 70,
    placement: 'surface',
  },
  {
    id: 'kitchen-sink',
    label: 'Sink cabinet',
    name: 'Sink',
    type: 'sink',
    category: 'kitchen',
    width: 80,
    ...COUNTER,
    placement: 'floor',
    clearance: KITCHEN_AISLE,
  },
  {
    id: 'stove',
    label: 'Stove',
    name: 'Stove',
    type: 'stove',
    category: 'kitchen',
    width: 60,
    ...COUNTER,
    placement: 'floor',
    clearance: KITCHEN_AISLE,
  },
  {
    id: 'fridge',
    label: 'Fridge-freezer',
    name: 'Fridge',
    type: 'appliance',
    category: 'kitchen',
    width: 60,
    depth: 65,
    height: 185,
    placement: 'floor',
    clearance: APPLIANCE_DOOR,
  },
  {
    id: 'fridge-side-by-side',
    label: 'Side-by-side fridge',
    name: 'Fridge',
    type: 'appliance',
    category: 'kitchen',
    width: 91,
    depth: 72,
    height: 178,
    placement: 'floor',
    clearance: APPLIANCE_DOOR,
  },
  {
    id: 'dishwasher',
    label: 'Dishwasher',
    name: 'Dishwasher',
    type: 'appliance',
    category: 'kitchen',
    width: 60,
    depth: 60,
    height: 85,
    placement: 'floor',
    clearance: APPLIANCE_DOOR,
  },
  {
    id: 'microwave',
    label: 'Microwave',
    name: 'Microwave',
    type: 'appliance',
    category: 'kitchen',
    width: 50,
    depth: 40,
    height: 30,
    placement: 'surface',
  },
  // Bathroom
  {
    id: 'toilet',
    label: 'Toilet',
    name: 'Toilet',
    type: 'toilet',
    category: 'bathroom',
    width: 38,
    depth: 65,
    height: 80,
    placement: 'floor',
    clearance: { enabled: true, front: 60 },
  },
  {
    id: 'washbasin',
    label: 'Washbasin',
    name: 'Washbasin',
    type: 'washbasin',
    category: 'bathroom',
    width: 60,
    depth: 45,
    height: 85,
    placement: 'floor',
    clearance: { enabled: false, front: 60 },
  },
  {
    id: 'vanity',
    label: 'Vanity unit with basin',
    name: 'Vanity unit',
    type: 'washbasin',
    category: 'bathroom',
    width: 80,
    depth: 48,
    height: 85,
    placement: 'floor',
    clearance: { enabled: false, front: 60 },
  },
  {
    id: 'shower',
    label: 'Shower',
    name: 'Shower',
    type: 'shower',
    category: 'bathroom',
    width: 90,
    depth: 90,
    height: 200,
    placement: 'floor',
    clearance: { enabled: false, front: 60 },
  },
  {
    id: 'shower-120',
    label: 'Shower',
    name: 'Shower',
    type: 'shower',
    category: 'bathroom',
    width: 120,
    depth: 80,
    height: 200,
    placement: 'floor',
    clearance: { enabled: false, front: 60 },
  },
  {
    id: 'bathtub',
    label: 'Bathtub',
    name: 'Bathtub',
    type: 'bathtub',
    category: 'bathroom',
    width: 170,
    depth: 75,
    height: 60,
    placement: 'floor',
    clearance: { enabled: false, front: 60 },
  },
  {
    id: 'washing-machine',
    label: 'Washing machine',
    name: 'Washing machine',
    type: 'washer',
    category: 'bathroom',
    width: 60,
    depth: 60,
    height: 85,
    placement: 'floor',
    clearance: APPLIANCE_DOOR,
  },
  {
    id: 'dryer',
    label: 'Tumble dryer',
    name: 'Dryer',
    type: 'washer',
    category: 'bathroom',
    width: 60,
    depth: 60,
    height: 85,
    placement: 'floor',
    clearance: APPLIANCE_DOOR,
  },
  ...TV_SIZES.map(tv),
  ...MONITOR_SIZES.map(monitor),
  {
    id: 'pc-tower',
    label: 'PC tower',
    name: 'PC tower',
    type: 'pc-tower',
    category: 'electronics',
    width: 22,
    depth: 47,
    height: 48,
    placement: 'floor',
  },
  {
    id: 'console',
    label: 'Game console',
    name: 'Game console',
    type: 'console',
    category: 'electronics',
    width: 11,
    depth: 26,
    height: 39,
    placement: 'surface',
  },
  {
    id: 'plant',
    label: 'Plant',
    name: 'Plant',
    type: 'plant',
    category: 'other',
    width: 50,
    depth: 50,
    height: 120,
    placement: 'floor',
    shape: ROUND,
    color: PLANT_GREEN,
  },
  {
    // Goes onto a desk, shelf or sideboard like a monitor, or onto the floor when dropped there.
    id: 'plant-small',
    label: 'Small plant',
    name: 'Plant',
    type: 'plant',
    category: 'other',
    width: 20,
    depth: 20,
    height: 30,
    placement: 'surface',
    flexiblePlacement: true,
    shape: ROUND,
    color: PLANT_GREEN,
  },
  {
    id: 'generic',
    label: 'Rectangular object',
    name: 'Object',
    type: 'generic',
    category: 'other',
    width: 60,
    depth: 40,
    height: 50,
    placement: 'floor',
  },
  {
    id: 'round-object',
    label: 'Round object',
    name: 'Object',
    type: 'generic',
    category: 'other',
    width: 50,
    depth: 50,
    height: 50,
    placement: 'floor',
    shape: ROUND,
  },
];

export const TYPE_LABELS: Record<FurnitureType, string> = {
  desk: 'Desk',
  'sit-stand-desk': 'Sit-stand desk',
  'l-desk': 'L-shaped desk',
  'office-chair': 'Office chair',
  chair: 'Chair',
  armchair: 'Armchair',
  pouf: 'Pouf / stool',
  sofa: 'Sofa',
  sideboard: 'Sideboard',
  shelf: 'Shelf',
  wardrobe: 'Wardrobe',
  bed: 'Bed',
  table: 'Table',
  'kitchen-cabinet': 'Kitchen cabinet',
  sink: 'Kitchen sink',
  stove: 'Stove',
  appliance: 'Appliance',
  toilet: 'Toilet',
  washbasin: 'Washbasin',
  shower: 'Shower',
  bathtub: 'Bathtub',
  washer: 'Washer / dryer',
  tv: 'TV',
  monitor: 'Monitor',
  'pc-tower': 'PC tower',
  console: 'Game console',
  plant: 'Plant',
  generic: 'Object',
};

export function findPreset(id: string): FurniturePreset | undefined {
  return PRESETS.find((p) => p.id === id);
}

/** Default preset per type, used to fill in missing fields on import. */
export function presetForType(type: FurnitureType): FurniturePreset {
  return PRESETS.find((p) => p.type === type) ?? PRESETS.find((p) => p.type === 'generic')!;
}
